"""add_notes_to_risk_flags

Revision ID: 2cb61514cf94
Revises: 3fe9020a97ed
Create Date: 2026-06-17 13:05:13.887677
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb61514cf94'
down_revision: str | None = '3fe9020a97ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_flags', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_flags', 'notes')
    # ### end Alembic commands ###
